### PR TITLE
Update `@deltachat/stdio-rpc-server` and `deltachat/jsonrpc-client` to 1.42.1 and minor npm dependency updates

### PR DESCRIPTION
**Pull request by nicodh**
* fix crash on windows #3959

for core updates see [Changelog](https://github.com/deltachat/deltachat-core-rust/blob/main/CHANGELOG.md)

### CODE REVIEW

**Comment by nicodh** [comment]
@Simon-Laux not sure what we should add here into CHANGELOG

**Comment by nicodh** [comment]
TODO: check wether we should handle the new property "quotedText" see [Just text quote](https://github.com/deltachat/deltachat-core-rust/issues/5695)

**Review by Simon-Laux — CHANGES_REQUESTED** [review]
package.json update and changelog updates are missing. for change log just look to previous versions and copy the line about the core update, if it could be interesting for  users also mention some of the changes of core below (in a nested list item.

**Comment by Simon-Laux** [comment]
> TODO: check wether we should handle the new property "quotedText" see https://github.com/deltachat/deltachat-core-rust/issues/5695

I think we just need to explicitly set it to `null` because of https://github.com/deltachat/yerpc/issues/10

**Pull request merged**
