### PR TITLE
Implement login instruction

### LINKED ISSUE #503: Make initial login more helpful
- Platform (linux):
- Delta Chat Desktop Version: current master

Currently the first login screen might be a bit confusing for newcomers as it not clear what you actually need to login to (it might be some delta chat account that I am supposed to create somewhere else first).

To make it more clear a formulation like "Login with an existing mail account (use your mail credentials here)" might be better.

scrot

### PR DESCRIPTION
**Pull request by Jikstra**
This implements a new language string which needs to get reviewed and implemented into the transifix stuff. 

screenshot_20190120_231747

Fixes #503

### CODE REVIEW

**Comment by Jikstra** [comment]
> So merging this will supersede #604 (which can be closed)

I'm fine with this as long as the commit history is somehow clean on those 2 features. Maybe we need to merge it via cli and not the squash & merge feature. Maybe it's easier to merge the other pr, than rebase this one on latest master?

**Comment by ralphtheninja** [comment]
> Maybe it's easier to merge the other pr, than rebase this one on latest master?

Aye, I prefer this as well.

**Comment by ralphtheninja** [comment]
So the last commit fixes the console.log from the other PR. I'll just make a normal merge and be done with it.

**Comment by Simon-Laux** [comment]
Can you add a guide linked in or in the readme that shows on how to the experimental tranalations feature? @Jikstra

**Comment by Jikstra** [comment]
@Simon-Laux good idea, will add a short description to readme. But not now ^^

**Pull request merged**
