### PR TITLE
Prepare release v1.48

### PR DESCRIPTION
**Pull request by nicodh**

### CODE REVIEW

**Comment by nicodh** [comment]
> the local offline help will get a downgrade by this PR - probably as `./bin/create-local-help.sh` was executed while having `../deltachat-pages/` checked out in an old state - you need to pull there (or, add that to the script, maybe also check if `main` is checked out)
> 
I was in fresh pulled state in deltachat-pages #86291b98bea add more redirects

Is there another script to be executed in pages before copying to desktop?

**Comment by nicodh** [comment]
I see the wrong chages now. I will investigate whats wrong...

**Comment by r10s** [comment]
> I was in fresh pulled state in deltachat-pages #86291b98bea add more redirects
>
> Is there another script to be executed in pages before copying to desktop?

you're right, `./bin/create-local-help.sh` creates the offline, assuming  HTML-files from `../deltachat-pages/_site` are up to date. they are created using `bundle exec jekyll build` - which requires some stuff on your computer.

to move forward now - i can do a separate PR if you like, things are working for me locally

**Comment by nicodh** [comment]
> i can do that in a separate PR if you like, things are working for me locally

Yes that would help, at least if we  want the newest help pages in desktop

**Comment by r10s** [comment]
the last update is only a few weeks ago, but i created https://github.com/deltachat/deltachat-desktop/pull/4325 , when we're anyways on that :)

**Review by r10s — APPROVED** [review]
yeah, much less code also now :)

**Pull request merged**
