### PR TITLE
add an experimental switch to disable font ligatures

### PR DESCRIPTION
**Pull request by Simon-Laux**
https://support.delta.chat/t/disabling-font-ligatures/1490

we could also think about changing the default, I'm not sure what option is better.

### CODE REVIEW

**Comment by Jikstra** [comment]
Is there any problem with just disabling font ligature? Don't like the idea of adding an option for something so subtle.

**Comment by r10s** [comment]
there was some request in the issue tracker at https://github.com/deltachat/deltachat-desktop/issues/2106 .

however, tbh, i would also not add such an option, at least not to the official settings and not in the usual "settings" dialog, no even as "experimental". that will come at cost, i do not think, this is worth maintaining.

there are much "larger" apps not having something like that. if someone is uncomfortable with the system font and the ligatures used, we should point him to changing this in the system settings.

**Comment by r10s** [comment]
i just checked signal and telegram desktop apps: i did not find such an option, but both seems to have ligatures disabled, at least if i type in `fi` that looks differently there. so, maybe, that is the more straight forward approach. however, compared to other things, i think, this is a really tiny detail :)

**Comment by Simon-Laux** [comment]
so we are for disabling it in general?

**Comment by Simon-Laux** [comment]
superseded by #2167

**Comment by r10s** [comment]
> so we are for disabling it in general?

_if_ there are really issues with ligatures, i think, this is the better approach, yes.

**Pull request closed without merging**
