### PR TITLE
add command to make portable builds

### PR DESCRIPTION
**Pull request by Simon-Laux**
related to https://support.delta.chat/t/please-make-deltachat-for-windows-a-truly-portable-standalone-program/675/8

### CODE REVIEW

**Comment by Jikstra** [comment]
I would suggest having one script which runs all commands to build all install files (skipping .dmg if we're not on a mac). I think this makes more sense than having x npm run scripts.

**Comment by Simon-Laux** [comment]
> I would suggest having one script which runs all commands to build all install files (skipping .dmg if we're not on a mac). I think this makes more sense than having x npm run scripts.

I totally agree, but I don't want to fiddle around with spawn process now. Let's keep this in mind for #1136

**Comment by ralphtheninja** [comment]
So this is done because a single user wanted a portable build?

**Comment by Simon-Laux** [comment]
I though it would be usefull even before they asked for it. Its useful in many cases and it gives freedom. Also for one user that speaks, most of the time many want it too.
I worked on the dl site and I can remove an ugly disclaimer there when providing the portable build.

Am 14. November 2019 00:21:09 MEZ schrieb Lars-Magnus Skog <notifications@github.com>:
>So this is done because a single user wanted a portable build?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/deltachat-desktop/pull/1138#issuecomment-553650448

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by STPKITT** [comment]
@ralphtheninja: Better then not doing it just because you don't like it. I mean wth? Btw I came up with this topic in the German DeltaChat XMPP group and multiple people wanted it. Only then I requested this in the Delta.Chat forum.

**Comment by Simon-Laux** [comment]
Don't panic. Lets keep this conversation civil.

> Better then not doing it just because you don't like it

Don't over-interpret @ralphtheninja's question @STPKITT. Lets assume its just a polite question.

**Comment by ralphtheninja** [comment]
@Simon-Laux @STPKITT is right. I could have used a better tone when asking this. Sorry about this.

**Comment by STPKITT** [comment]
All good :-)

**Pull request merged**
