### PR TITLE
Label Icon Buttons for accessibility

### PR DESCRIPTION
**Pull request by Simon-Laux**
#870
@OzancanKaratas please test if that works the way you want.
Also the text is in `_locales/_experimental_en.json` if you want to change it to sound better.

### CODE REVIEW

**Comment by Simon-Laux** [comment]
I would wait a bit with moving "a11y_goto_media_label" and "a11y_goto_chat_label" because they might become a dialog soon @jikstra

**Comment by OzancanKaratas** [comment]
@Simon-Laux I will test it but you should release a Windows version.

**Comment by OzancanKaratas** [comment]
Screen readers does not love prefixes like button, link. Because it already speaks the prefixes. Please remove it. It should be:

Send button = Send

**Comment by Simon-Laux** [comment]
Ok, what about the delivery status labels? are they ok or should they just say sent/delivered/read and so on?

**Comment by OzancanKaratas** [comment]
I don't see a problem. However, I should try a compiled version.

**Pull request merged**
