### PR TITLE
Changed default english signature text

### PR DESCRIPTION
**Pull request by KylePiira**
Changed "Sent with my Delta Chat Messenger" to "Sent via Delta Chat Messenger" which sounds more natural.

### CODE REVIEW

**Comment by Simon-Laux** [comment]
Did you change it in transifex too?

**Comment by KylePiira** [comment]
@Simon-Laux Nope. I tried signing up for the Delta Chat Transifex group but it doesn't seem that I have permission to edit the source language strings.

**Comment by Simon-Laux** [comment]
I think you can request access somehow and I can approve you join request (I'm not super familiar with transifex)

**Comment by KylePiira** [comment]
I'm not all that familiar with Transifex either. When I joined the group it required me to pick another language to translate (I picked Spanish because English was not an option), however, after approval it seems I can only modify the Spanish strings.

**Comment by Simon-Laux** [comment]
Ok changing the english strings seems to be impossible from transifex because its the source language.
I recommend filing an issue on the https://github.com/deltachat/deltachat-android repo for this string to be changed in this case.

**Comment by KylePiira** [comment]
Alright will do.

**Pull request closed without merging**
