### PR TITLE
fix: a11y: keyboard navigation: add outline and focusability

### PR DESCRIPTION
**Pull request by WofWca**
See commit messages

I tested it. Appears to be working good, but some rarely used elements might get ugly even for mouse-only navigation.

This by no means makes DC fully keyboard-accessible, but it's an improvement.

### CODE REVIEW

**Comment by Simon-Laux** [comment]
seems to work though the majority of the app still isn't focusable:
- accounts in sidebar
- tabs (qr code scanner dialog, gallery
- items in gallery
- Images in messages
- toggle switches in settings
- appearance settings, theme selector button and wallpapers

We can also track those in a new issue.

I don't really like the visual style of the outline (orange + white) yet, but maybe I'll get used to it.

also outline should probably have the highest z-index so it is always fully visible:
Bildschirmfoto 2024-07-05 um 00 44 02
(in the settings it's currently cut off)

**Review by Simon-Laux — APPROVED** [review]

**Comment by r10s** [comment]
is the outline always visible or only after tab is hit?

is there a selector for high-contrast or accessibility maybe? what do others (signal, whatsapp) do here?

**Comment by WofWca** [comment]
> highest z-index so it is always fully visible

I'm not sure if there is a way to set Z index on the outline, but you can try to set negative `outline-offset` for such cases. Or just highlight the item some other way, e.g. with the blackground color change.
The way I think about this change is to have accessibility by default for all elements.

> is the outline always visible or only after tab is hit?

Only after Tab is hit.

> is there a selector for high-contrast or accessibility maybe?

I believe so.

**Comment by WofWca** [comment]
> what do others (signal, whatsapp) do here?

Signal appears to behave the same, but they do it programmatically, by [dynamically adding `.keyboard-mode` class](https://github.com/signalapp/Signal-Desktop/blob/b34f2fbb99d68bd462715f8519524100580fb372/ts/services/InteractionMode.ts#L24).

**Pull request merged**
