### PR TITLE
style: add CSS transition for adding reaction

### PR DESCRIPTION
**Pull request by WofWca**
This doesn't add width transition for narrow messages though.

https://github.com/deltachat/deltachat-desktop/assets/39462442/618ad90e-1b8e-436a-980a-83926ec30d63

### CODE REVIEW

**Comment by WofWca** [comment]
Please also keep in mind #3753. Maybe fixing that will make this MR irrelevant, but this is a small but nice change.

**Comment by hpk42** [comment]
again, could you rebase and embedd a small video to ease reviewing?

**Comment by WofWca** [comment]
Updated

**Comment by farooqkz** [comment]
@Simon-Laux The change is so trivial. maybe simply merge it? Or perhaps give me more time to fix #3753

**Pull request merged**
