### PR TITLE
Add media view. Fixes #268

### LINKED ISSUE #268: Media view
View all media for a chat.

### PR DESCRIPTION
**Pull request by karissa**

### CODE REVIEW

**Comment by Jikstra** [comment]
Very nice, looks good. We should put this in a dialog maybe at some point.

**Comment by karissa** [comment]
@Jikstra I don't think it should be in a dialog because it's based on the currrent chat you're viewing.

**Comment by Simon-Laux** [comment]
#462

**Comment by Simon-Laux** [comment]
`Very nice, looks good. We should put this in a dialog maybe at some point.`
Or in a sidebar - it depends on how we want to use it.

**Comment by karissa** [comment]
@Simon-Laux yeah, I think Slack puts it in a sidebar, right?

**Comment by Simon-Laux** [comment]
@karissa I can't tell, cause I didn't used slack yet

**Pull request merged**
