### PR TITLE
Use empty placeholder to avoid rendering overhead

### PR DESCRIPTION
**Pull request by nicodh**
I tested with an acoount with ~600 chats.
Since the chatlist renders a skeleton for each item upfront there is quite some overhead with 600 chat items.. 

I tested using just an empty div with fix height as skeleton and while one might say that it not looks as nice as before it really improves performance.
See 3 profiles attached (can be loaded in Chrome dev tools)
The difference is probably only noticeable with many chats but there it is evident...

The breath animation seems also expensive if you look at the profiles...

[Profiles.zip](https://github.com/deltachat/deltachat-desktop/files/3991583/Profiles.zip)

### CODE REVIEW

**Comment by Simon-Laux** [comment]
I don't believe that that is where the performance loss is.
I'll try to reproduce and look at the profiles soon.
maybe there is some css that allows us to only render empty placeholders when they are outside the view?

**Comment by Simon-Laux** [comment]
Sure we can make the placeholders simpler to save on render time, maybe even use an image?

**Comment by Simon-Laux** [comment]
> The breath animation seems also expensive if you look at the profiles...

I didn't see that, only that the animations are active for a long time. But I probably just don't know how to interpret the profiler.

**Comment by Jikstra** [comment]
The animations shouldn't happen if the chat is not in view. This should be easy to implement as the useLazyChatList stuff implements this already,

**Comment by nicodh** [comment]
> But a real virtual list should be the way to go no matter what
I don't get what you mean by that? The chat list is already a virtual list...
Do you want to get rid of the placeholder? The animations were only applied to the placeholder which should not be visible in most cases.

What is your opinion about the empty skeletons? Do you agree to leave them empty? Would you prefer some background image to make them look like before?
I think the better performance justifies to have empty items instead of more realistic looking placeholders

**Comment by Jikstra** [comment]
> I don't get what you mean by that? The chat list is already a virtual list...

It's not. A virtual list would only keep the items rendered. Currently we have a lazy loading list. Once you scrolled down all chat items are in the dom. I think a hotfix to render them empty is fine, but looks shit. I would try to figure out a way to only render/animate the placeholder ones that are in view.

**Comment by nicodh** [comment]
ok. So maybe merge this PR in yours and then add some stuff to make the skeletons look nicer? I will test performance then with my 600 chat account..

**Comment by Simon-Laux** [comment]
> I think a hotfix to render them empty is fine, but looks shit

exactly it looks bad. You can throw out the animation if that eats too much performance, it not important at all.
Using an image might help because it would only need to be rendered once and just repeated, I'll guess.
At the moment the placeholder has like 4-8 sub elements, we can simplify the placeholder by using less elements, maybe web components could help us here? @nicodh

**Comment by Simon-Laux** [comment]
we could use https://css-tricks.com/building-skeleton-screens-css-custom-properties/ to build a skeleton that doesn't need extra elements.

**Comment by nicodh** [comment]
For me the empty item would be totally fine - it's only visible for fractions of a second anyway so I wouldn't put too much effort in it. But these css skeletons seem a good solution.

**Pull request merged**
