### PR TITLE
Add padlock to messages + tweak conversation grey

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/deltachat/deltachat-desktop/issues/144 

Darkened the default grey to get a better contrast to the shield/padlock. Couldn't find a proper padlock so used the shield for now.

Result:

screenshot from 2018-10-25 14-56-17

### CODE REVIEW

**Comment by ralphtheninja** [comment]
> maybe we should have a repo for such things.

Definitely!

**Comment by ralphtheninja** [comment]
Updated:

screenshot from 2018-10-25 18-17-13

**Comment by r10s** [comment]
great :)

**Comment by karissa** [comment]
nice

**Pull request merged**
