### PR TITLE
Update electron to v6.1.9

### PR DESCRIPTION
**Pull request by Jikstra**

### CODE REVIEW

**Comment by Jikstra** [comment]
@r10s can you try out the mac os preview build and tell us if the menu is working again? In electron v6.1.8 some mac/menu specific things got fixed

**Comment by r10s** [comment]
@Jikstra thanks for pushing that forward, however, it does not make a difference on mac yet :/

**Comment by r10s** [comment]
@Jikstra but ....................... 

the qr-code-scanning is working on mac with this version \o/ just did a verification between mac-desktop and ios :) so, this fixes #1586 :)

**Comment by Jikstra** [comment]
@Simon-Laux didn't you fix something for the mac keybindings or something? Could this be a source of the problem?

**Comment by Simon-Laux** [comment]
That code could be the source of the problem if it fails on mac, but shouldn't this throw some-kind of error?
Also I can't explain what the menu has to do with the setting to have no system title bar.

**Pull request merged**
