### PR TITLE
Image zoom for full screen media view

### PR DESCRIPTION
**Pull request by flipsimon**

### CODE REVIEW

**Comment by Jikstra** [comment]
Geiloooo!
One thing, can you do `git checkout origin/master package-lock.json` and commit the original package-lock.json file?

**Comment by flipsimon** [comment]
Using the original package-lock file leads to errors as it's not synced to the package.json file anymore which contains react-zoom-pan-pinch. What should I do in this case?

**Comment by Jikstra** [comment]
> Using the original package-lock file leads to errors as it's not synced to the package.json file anymore which contains react-zoom-pan-pinch. What should I do in this case?

Oh I think I was stupid. Of course we need a new package-lock.json if you added a dependency. Sorry :D

**Comment by Jikstra** [comment]
Awwwesome!

**Pull request merged**
