### PR TITLE
use stdio binary instead of dc node & update electron to 30 & update min node to 20

### PR DESCRIPTION
**Pull request by Simon-Laux**
Todo:
- [ ] account migration function in core
- [X] port into own npm module that has all the prebuilds somehow
- [x] remove open multiple instances parameter
- [x] issue when closing deltachat 
- [ ] code review from "experts" -> fix linereader/performance
- [ ] optimise with regex or use `split2` package (https://github.com/mcollina/split2/blob/master/index.js) -> to make it more correct with `/\r?\n/`

This experiment came from a hacking session together with @Jikstra.

depends on:
- https://github.com/deltachat/deltachat-core-rust/pull/5332

### CODE REVIEW

**Comment by Simon-Laux** [comment]
I got this when closing DC:
```
See the logfile (~/Library/Application Support/DeltaChat/logs/2023-11-25-23-28-44.log) for details and contact the developers about this issue:
{"message":"Object has been destroyed","stack":"TypeError: Object has been destroyed\n    at Object.send (~/Coding/deltachat-desktop/src/main/windows/main.ts:167:14)\n    at StdioServer.on_data (~/Coding/deltachat-desktop/src/main/deltachat/controller.ts:83:18)\n    at Socket.<anonymous> (~/Coding/deltachat-desktop/src/main/deltachat/stdio_server.ts:44:16)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Socket.push (node:internal/streams/readable:234:10)\n    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)"}
```

**Comment by Simon-Laux** [comment]
The ci error: 
```
If the '@deltachat/jsonrpc-client' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module '@deltachat/jsonrpc-client';`
```

will be fixed with a new release of it after https://github.com/deltachat/deltachat-core-rust/pull/5332 is merged

**Comment by Simon-Laux** [comment]
if you get an permission error, you can fix it with:
```
chmod +x node_modules/@deltachat/stdio-rpc-server-*-*/deltachat-rpc-server
```

**Comment by nicodh** [comment]
With import of @deltachat/stdio-rpc-server and @deltachat/jsonrpc-client I have 2 errors:
1. I have to change permissions to @deltachat/stdio-rpc-server-linux-x64 to allow execution, otherwise I get an EACCES error
2. after that I electron crashes with signal SIGSEGV without telling after what command

I'm trying to debug where the crash happens but so far no luck...

**Comment by nicodh** [comment]
On Mac Catalina 10.15.7 this branch is partly working. I get 
```
child process exited with code null
child process close all stdio with code null
```
in the logs (after trying to send a message)
`{"message":"write EPIPE","stack":"Error: write EPIPE\n    at afterWriteDispatched (node:internal/stream_base_commons:160:15)\n    at writeGeneric (node:internal/stream_base_commons:151:3)\n    at Socket._writeGeneric (node:net:952:11)\n    at Socket._write (node:net:964:8)\n    at writeOrBuffer (node:internal/streams/writable:564:12)\n    at _write (node:internal/streams/writable:493:10)\n    at Socket.Writable.write (node:internal/streams/writable:502:10)\n    at StdioServer.send (file:///Users/ndh/projects/deltachat/deltachat-desktop/src/main/deltachat/stdio_server.ts:44:32)\n    at file:///Users/ndh/projects/deltachat/deltachat-desktop/src/main/deltachat/controller.ts:140:28\n    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82809)"}`

**Comment by Simon-Laux** [comment]
would be interesting if you could find out shat message it sent to the stdio binary. I can not reproduce this on macOS Sonoma 14.3.1

**Pull request merged**
