### PR TITLE
Chatlist refactoring

### PR DESCRIPTION
**Pull request by ralphtheninja**
@nicodh did some really awesome work and this contains a lot of improvements. We should merge this as is and later on @nicodh can continue on sorting.

Closes https://github.com/deltachat/deltachat-desktop/issues/788
Closes https://github.com/deltachat/deltachat-desktop/issues/757

### CODE REVIEW

**Comment by Jikstra** [comment]
What's the difference between this and https://github.com/deltachat/deltachat-desktop/pull/801?
Also there's some standard fix missing.

**Comment by ralphtheninja** [comment]
The difference is that this has been rebased.

**Comment by ralphtheninja** [comment]
@Jikstra Standard fixed. I went through the backlog and this closes _at least_ two issues :wink:

**Comment by Jikstra** [comment]
@ralphtheninja is this pr more or less usable? Because nicos introduced some bugs/things that weren't implemented. I would love to merge this pr, but don't want to introduce half working thins :)

**Comment by Simon-Laux** [comment]
We should check for those issues when merging:
Issues that might disappear with #801: (but test with c and rust core)

--Switch account while new messages are fetched results in a small freeze #702
--Chat updates (such as delete or new incomming message) result in jumping to the end #712
--Leaving an freshly created group #697
--Typing a message is slow #802 
--New message counter on selected chat doesn't update immediately #757
--If a lot of messages are incoming, don't re-render all the time #781

**Comment by ralphtheninja** [comment]
@Jikstra It's definitely usable.

**Comment by ralphtheninja** [comment]
Please have a look and test as well. I don't know what you mean with half working things. It puts the application in a better state than before.

**Comment by Jikstra** [comment]
@ralphtheninja https://github.com/deltachat/deltachat-desktop/issues/831 this one for example. I think it's fine to merge this and just fix whatever is not working.

**Pull request merged**
