### PR TITLE
Indicate who forwarded a message in groups

### PR DESCRIPTION
**Pull request by Jikstra**
Screenshot_20210210_105056
Screenshot_20210210_105041

Fixes https://github.com/deltachat/deltachat-desktop/issues/1977

### CODE REVIEW

**Review by Simon-Laux — CHANGES_REQUESTED** [review]
LGTM, but don't forget to update the part in the change-log to represent the current state of the translation update:
```
- update translations (mid dezember 2020)
```

**Comment by r10s** [comment]
nice! please show the message also in a forwarding-grey color as suggested in #1977
- to make it more clear, that this is not a message that was "typed in" 
- to let groups and one-to-ones stay visually different (we do not have the user-colors in one-to-ones)
- to stay visually compatible with android/ios

**Comment by Jikstra** [comment]
@r10s so you mean showing the "Forwarded by..." line in the grey instead of the user color? It hurts a little bit my eyes, but for sure it sticks out :P

**Comment by r10s** [comment]
> so you mean showing the "Forwarded by..." line in the grey instead of the user color? It hurts a little bit my eyes, but for sure it sticks out :P

yip. tried to explain it in some details :)  sorry for your eyes :) but i think, a bit of grey make the remaining colors even more beautiful 🌹

and in addition, i would stay with the string "forwarded message" in one-to-one chats, also in grey then (not sure if that is changed by this pr as well)

**Pull request merged**
