### PR TITLE
[wip] Add links video chat dialog

### PR DESCRIPTION
**Pull request by Jikstra**
Screenshot_20220504_155331

- [ ] Fix weird radio behaviour

### CODE REVIEW

**Comment by Simon-Laux** [comment]
what's `Fix weird radio behaviour`?

**Comment by obsoleszenz** [comment]
> what's `Fix weird radio behaviour`?

Try it out and you will see it, basically not the element you clicked on is getting selected.

**Comment by Simon-Laux** [comment]
maybe we should avoid using blueprint when fixing this?

**Comment by farooqkz** [comment]
Oh you folks were giving me a heart attack. I thought my PR has caused the weird radio button behavior. Now I see my PR rather fixed it :D

**Comment by Simon-Laux** [comment]
> Does this PR add anything to it?

This pr is the old one that attempted it, we can close it, it is ancient.

**Pull request closed without merging**
