### PR TITLE
add verified checkmark into chat title in navbar

### LINKED ISSUE #1368: Add verified-checkmark right of Group-title (like Android)
Currently only the chatlist shows a verified-checkmark. 
The group-title above the message-list should also show a verified-checkmark like on Android. 
This makes it easier to quickly check if i am writing in a "secure" channel.

### PR DESCRIPTION
**Pull request by Simon-Laux**
closes #1368

### CODE REVIEW

**Comment by r10s** [comment]
can we have the icon _right_ of the name please?
preferably also in the chatlist?

however, this should not block merging, it's already a great improvement :)

**Comment by Simon-Laux** [comment]
sure we can have it on the right side, in the Chat I wouldn't move it to the right, I would prefer to move it to overlay the corner of the avatar like iOS does it.

**Comment by r10s** [comment]
>  I would prefer to move it to overlay the corner of the avatar like iOS does it

yip, that's also good, also security-wise better as users cannot be tricked by adding some emoticons to the title. ios does the same for the title bar btw.

**Comment by Simon-Laux** [comment]
well we don't have the avatar in the title bar.

**Comment by r10s** [comment]
> well we don't have the avatar in the title bar.

i think it should be added anyway.

**Comment by Simon-Laux** [comment]
sure? we removed it "recently" because it wasn't round and we decided that it doesn't need to be in there anyway.

**Comment by Simon-Laux** [comment]
We could try how it looks I'm not against it.

**Comment by r10s** [comment]
> sure? we removed it "recently" because it wasn't round and we decided that it doesn't need to be in there anyway.

yip, sure :)
and yes, it should be round then.
but it is not urgent in any way and not needed for now.

**Pull request merged**
