### PR TITLE
Restyle buttons in create chat

### PR DESCRIPTION
**Pull request by Jikstra**
for search input. This currently removes the possibility to clear the search input which is a regression, but maybe only a small one. Putting in a js version of this should be doable.

### CODE REVIEW

**Comment by hpk42** [comment]
nice ;)

**Comment by Jikstra** [comment]
@ralphtheninja @Simon-Laux maybe lets add in the old cancel button even if it's ugly? Better than to not have one.

**Comment by ralphtheninja** [comment]
> @ralphtheninja @Simon-Laux maybe lets add in the old cancel button even if it's ugly? Better than to not have one.

I have no strong opinion. Do what you feel like is best :)

**Comment by Simon-Laux** [comment]
I don't care about that button, I rarely use such buttons anyway... Rather remove it before the release and add a better version later I would say

**Comment by Jikstra** [comment]
I'm going to keep it in and replace it at some other point.

**Pull request merged**
