### PR TITLE
WIP: Implement account sidebar to quickly switch between accounts

### PR DESCRIPTION
**Pull request by missytake**
Small hacking session with @Jikstra :) (I don't really know typescript)

- [x] messagelist doesn't update yet when switching account
- [x] "connecting..." toast needs to be margin-lefted or overlayed
- [x] some account changes don't work yet
- [x] + icon to add more accounts
- [x] add experimental feature flag
- [x] highlight selected account
- [ ] account_add is broken; it reconfigures the currently selected account instead of creating a new one.
- [ ] the sidebar doesn't refresh, when an account is added.

Screenshot_20220222_003847

Fixes https://github.com/deltachat/deltachat-desktop/issues/2331

### CODE REVIEW

**Comment by missytake** [comment]
Sooo I found a bug in this branch ;)

**expected behavior:** when I add a new account, I get redirected to it and can use it.
**actual behavior:** when I add a new account, I get redirected to the account I had selected beforehand. The new account does *not* appear, neither in the sidebar nor in the account switcher. I get 2 new device messages, but in the old account :D

**Comment by missytake** [comment]
oh *actually* I think the accounts were *merged*. I see mails to both my new account and my old account in the old one account now xD this is weeeeird

**Comment by missytake** [comment]
So my old account now authenticates with the credentials of the new account, and new chats are created through this connection. But it kept the profile pic and settings etc.

**Comment by missytake** [comment]
Okay, so:

1. account_add is broken; it reconfigures the currently selected account instead of creating a new one.
2. the sidebar doesn't refresh, when an account is added.

**Comment by missytake** [comment]
At some point after using this branch, I get another weird bug - but not sure if it's this branch or whether it's on master already. I'I will use master for a while now to see if it re-appears.

- expected behavior: desktop client connects and downloads messages as usual.
- actual behavior: desktop client shows SMTP as connected, and sending out messages works; but with IMAP it stays yellow, at "connecting...". The log shows the following error: `9.5s [w]core/event: 42 DC_EVENT_WARNING 0 src/scheduler.rs:176: fetch_new_messages: database disk image is malformed: Error code 11: The database disk image is malformed`

My workaround so far: export a backup, delete the .config/DeltaChat directory, re-import the backup. This fixes it for a while. Let's see if it reappears with the master branch...

**Comment by Jikstra** [comment]
> At some point after using this branch, I get another weird bug - but not sure if it's this branch or whether it's on master already. I'I will use master for a while now to see if it re-appears.
> 
>     * expected behavior: desktop client connects and downloads messages as usual.
> 
>     * actual behavior: desktop client shows SMTP as connected, and sending out messages works; but with IMAP it stays yellow, at "connecting...". The log shows the following error: `9.5s [w]core/event: 42 DC_EVENT_WARNING 0 src/scheduler.rs:176: fetch_new_messages: database disk image is malformed: Error code 11: The database disk image is malformed`
> 
> 
> My workaround so far: export a backup, delete the .config/DeltaChat directory, re-import the backup. This fixes it for a while. Let's see if it reappears with the master branch...

@missytake don't really think this has something to do with this branch but who knows? Another question, is the adding a new account fixed with my last commit?

**Comment by missytake** [comment]
Hm, the rebase introduced quite many errors... maybe this was a bad idea. do you still have the pre-rebased state on your branch, can you force-push it?

**Comment by missytake** [comment]
It's probably not so hard to fix, I just merged around a bit optimistically and pushed too early

**Comment by Simon-Laux** [comment]
I think we would have to redo this, it also was done before the hamburger-menu-sidebar existed.
I still like the idea of fast account switching and I think we should discuss general desktop UI design sometime, possible at an IRL meeting with pen an paper or in a call with penpot/figma

**Pull request closed without merging**
