### PR TITLE
Update rpgp version to 0.2.1

### PR DESCRIPTION
**Pull request by Jikstra**
This also needs that we update the docker travis image https://hub.docker.com/r/deltachat/travis-dc-node-base . I don't know how to push that image, but updated the Dockerfile. @flub can you help out?

### CODE REVIEW

**Comment by flub** [comment]
Hmm, i'm not sure.  The Dockerfile used to be in this repo in as `docker/Dockerfile` but it's gone?  /cc @ralphtheninja

**Comment by ralphtheninja** [comment]
It's still in this repo? https://github.com/deltachat/deltachat-desktop/blob/master/docker/Dockerfile

**Comment by Jikstra** [comment]
> Hmm, i'm not sure. The Dockerfile used to be in this repo in as `docker/Dockerfile` but it's gone? /cc @ralphtheninja

It's still there, i modified it in this PR too :D

https://github.com/deltachat/deltachat-desktop/pull/844/files#diff-ebacf6f6ae4ee68078bb16454b23247d

It's only about pushing a new image to the deltachat group/docker account that i dont know how to do it.

**Comment by flub** [comment]
oh wait.  desktop, not node.  oops.

anyway, `docker build -t deltachat/travis-dc-node-base:latest docker/` `docker push -t docker push deltachat/travis-dc-node-base:latest` should do it.  You're a member of the deltachat org on docker hub so should have permissions to do so, but if you prefer i'm happy to push it too (might be faster)

**Comment by Jikstra** [comment]
>  but if you prefer i'm happy to push it too (might be faster)

Yup would be happy if you can do it :)

**Pull request merged**
