### PR TITLE
Refactor Autocrypt and it's settings

### PR DESCRIPTION
**Pull request by Jikstra**
- Factor out encryption settings into dialogs/Settings-Encryption.tsx
- Move SendAutocryptSetupMessage dialog into Settings-Encryption because
it's only opened from there
- Refactor SendAutocryptSetupMessage dialog to use react hooks
- Refactor EnterAutocryptSetupMessage dialog to use react hooks
- Get rid of old style rpc and use DeltaBackend.call instead for
autocrypt calls

### CODE REVIEW

**Comment by Simon-Laux** [comment]
> Get rid of old style rpc and use DeltaBackend.call instead for
autocrypt calls

great, I had this on my todo list, too.

**Comment by Jikstra** [comment]
Dark mode is not on my priority list and won't work on it for the moment. But feel free to fix it, but please not in this pr :)

**Comment by Jikstra** [comment]
This would need a new -node version that will break the 1.3 release series. Or shall i deprecate the old api and add another method with a different name? @Simon-Laux what do you think?

**Comment by Simon-Laux** [comment]
@Jikstra Lets deprecate the old method and add a new one with another name.

**Pull request merged**
