### PR TITLE
Add imap folder configuration

### LINKED ISSUE #301: Add imapFolder configuration
Once https://github.com/deltachat/deltachat-node/issues/181 is done and released

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes #301

### CODE REVIEW

**Comment by hpk42** [comment]
hum, not sure if we actually make the folder configurable for the upcoming release.  Maybe we just make "watch INBOX" and "watch DeltaChat" two boolean options in advanced settings (and both would be on by default). @r10s what's your current take?

**Comment by karissa** [comment]
yeah let's wait on this until we have some UX input from @r10s , also curious what xenia and vadym think

**Comment by r10s** [comment]
yeah, i would also wait a bit until the shared-account-ships comes to calmer water :)

in fact, imap_folder option is currently deprecated (it will still work, but i do not think the option will stay under this name)

**Comment by webratte** [comment]
Since you have in Android Client (dev-version)

- Watch inbox folder

- Watch sent folder

- Watch deltachat folder

you also put this options in the desktop client.
I use only the deltachat folder (mails to a DC aliasadress will moved there via server side filter) to watch.
The current desktop client (v. 0.97.0-preview) seems only watch the inbox. So I can't keep my messages in sync between Android and Desktop.

**Comment by webratte** [comment]
Hi,
will you not implement this?
So the desktop client will be useless for users like me who use a Alias adress for DC and only the DC folder :-(

See also my last post.

**Comment by hpk42** [comment]
i thikn this was closed by mistake -- the android "imap options" should also be in desktop.

**Comment by hpk42** [comment]
oh, but this PR is about a specific variant of imap folder options (setting the name of the folder i think).  so actually it is fine to close this -- the PR for desktop to implement imap options needs to look differently.

**Comment by webratte** [comment]
> the android "imap options" should also be in desktop.

OK, sounds good to me and I think it's amust have 👍

**Comment by hpk42** [comment]
see also https://github.com/deltachat/deltachat-desktop/issues/508

**Pull request closed without merging**
