### PR TITLE
Fix constants in serverFlags conversion

### PR DESCRIPTION
**Pull request by link2xt**
This addresses #1025

### CODE REVIEW

**Comment by link2xt** [comment]
Traced it back to https://github.com/deltachat/deltachat-desktop/commit/2468dc5cf72d86226411eddf15f831366f0bff51

It survived two refactorings since then :)

**Comment by Jikstra** [comment]
@link2xt the integration tests fail if you create a pull request from your own repo to prevent people from hijacking our login credentials used on the ci. So in case you want to have integration tests, feel free to push to this repo.

**Comment by link2xt** [comment]
@Jikstra It seems I don't have permissions to push branches to the deltachat-desktop repo

**Comment by Jikstra** [comment]
@link2xt added you to contributors :)

**Pull request merged**
