### PR TITLE
remove single folder compat message.

### PR DESCRIPTION
**Pull request by karissa**
depends upon https://github.com/deltachat/deltachat-node/pull/210

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Can still merge this without #210 being done, just not release it.

**Comment by karissa** [comment]
I was hoping we would be able to make a release before merging this because there are some more critical bug fixes and features we could get in, and it seems like 0.30 is stalled today

**Comment by karissa** [comment]
unless you think it's fine and we can just merge it?

**Comment by hpk42** [comment]
On Wed, Dec 19, 2018 at 09:11 -0800, Karissa McKelvey wrote:
> unless you think it's fine and we can just merge it?

technically it can go after the new core and the second imap thread
is started properly in desktop.  practically it can be merged now ;)

**Pull request merged**
