### PR TITLE
Merge in dependencies from conversation

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by hpk42** [comment]
why does it make sense to remove the test code?

**Comment by ralphtheninja** [comment]
> why does it make sense to remove the test code?

I just thought we wouldn't need it. Can revert.

**Comment by hpk42** [comment]
I don't know if feasible but if the now-inline conversations evolves it'd be good to run/evolve the tests as well ...

**Comment by Jikstra** [comment]
> why does it make sense to remove the test code?

Can keep them for now, when we looked at it for a glimpse, they didn't look very helpful BUT it looks like they aren't unhelpful on a second look. Should keep them.

@ralphtheninja LGTM

**Pull request merged**
