### PR TITLE
Refactor message meta data component

### PR DESCRIPTION
**Pull request by adzialocha**

### CODE REVIEW

**Comment by adzialocha** [comment]
Let me know if the issue disappeared for you or if it's still reproducible! Thank you!

**Review by Simon-Laux — APPROVED** [review]
LGTM

**Comment by adzialocha** [comment]
Oupsi, still didn't fix the issue. It's some funky race condition, but I think I understand what's going on (something about the keys per message), will investigate

**Comment by adzialocha** [comment]
I'll merge this for now as a nice refactor but not as a fix. For the actual fix we might need more time and I'm not sure if that's a priority

**Pull request merged**
