### PR TITLE
Fix path in package asar

### LINKED ISSUE #3858: Map doesn't open
- Operating System (Linux/Mac/Windows/iOS/Android): xubuntu 22.04
- Delta Chat Version: 1.45.0, installed via .deb
- Expected behavior: when I click on the map icon on the top right of the selected chat window, the map opens.
- Actual behavior: nothing happens.
- Steps to reproduce the problem:
  - open desktop
  - click on the map icon
- Logs:
```
Error occurred in handler for 'open-maps-webxdc': {
  code: -1,
  message: 'failed to open file /opt/DeltaChat/resources/app.asar/html-dist/xdcs/maps.xdc\n' +
    '\n' +
    'Caused by:\n' +
    '    Not a directory (os error 20)'
}
```

### PR DESCRIPTION
**Pull request by nicodh**
resolves #3858

### CODE REVIEW

**Review by Simon-Laux — APPROVED** [review]
code lgtm, works locally, only needs a changelog entry (and maybe a rebase)

**Comment by missytake** [comment]
the CI fails with a related error?

**Comment by Simon-Laux** [comment]
> the CI fails with a related error?

electron builder somehow fails, but only on linux and it works locally. this pr already improves the bug from blocking to be just a ci bug, so I'd merge it as it and we can address the ci issue later.

**Comment by Simon-Laux** [comment]
ups I removed the explicit file paths pr

**Comment by Simon-Laux** [comment]
after rebase the issue also affects macOS ci (which was broken completely before, but now it has the same "file already exists" error as linux)

**Comment by Simon-Laux** [comment]
The errors for future reference (ci logs are not kept forever):

Linux:
```
  • map async       taskCount=74
  • exited          command=app-builder code=0 pid=2152
  • async task error  error=EEXIST: file already exists, link '/home/runner/work/deltachat-desktop/deltachat-desktop/html-dist/xdcs/maps.xdc' -> '/home/runner/work/deltachat-desktop/deltachat-desktop/dist/linux-unpacked/resources/app.asar.unpacked/html-dist/xdcs/maps.xdc'
  • async task error  error=EEXIST: file already exists, link '/home/runner/work/deltachat-desktop/deltachat-desktop/html-dist/xdcs/maps.xdc' -> '/home/runner/work/deltachat-desktop/deltachat-desktop/dist/linux-unpacked/resources/app.asar.unpacked/html-dist/xdcs/maps.xdc'
  ⨯ EEXIST: file already exists, link '/home/runner/work/deltachat-desktop/deltachat-desktop/html-dist/xdcs/maps.xdc' -> '/home/runner/work/deltachat-desktop/deltachat-desktop/dist/linux-unpacked/resources/app.asar.unpacked/html-dist/xdcs/maps.xdc'  failedTask=build stackTrace=Error: EEXIST: file already exists, link '/home/runner/work/deltachat-desktop/deltachat-desktop/html-dist/xdcs/maps.xdc' -> '/home/runner/work/deltachat-desktop/deltachat-desktop/dist/linux-unpacked/resources/app.asar.unpacked/html-dist/xdcs/maps.xdc'
    at link (node:internal/fs/promises:1052:10)
    at FileCopier.copy (/home/runner/work/deltachat-desktop/deltachat-desktop/node_modules/builder-util/src/fs.ts:247:5)
```

MacOS:
```
  • map async       taskCount=232
  • exited          command=app-builder_arm64 code=0 pid=4803
  • async task error  error=EEXIST: file already exists, link '/Users/runner/work/deltachat-desktop/deltachat-desktop/html-dist/xdcs/maps.xdc' -> '/Users/runner/work/deltachat-desktop/deltachat-desktop/dist/mas-universal-x64-temp/Electron.app/Contents/Resources/app.asar.unpacked/html-dist/xdcs/maps.xdc'
  • async task error  error=EEXIST: file already exists, link '/Users/runner/work/deltachat-desktop/deltachat-desktop/html-dist/xdcs/maps.xdc' -> '/Users/runner/work/deltachat-desktop/deltachat-desktop/dist/mas-universal-x64-temp/Electron.app/Contents/Resources/app.asar.unpacked/html-dist/xdcs/maps.xdc'
  ⨯ EEXIST: file already exists, link '/Users/runner/work/deltachat-desktop/deltachat-desktop/html-dist/xdcs/maps.xdc' -> '/Users/runner/work/deltachat-desktop/deltachat-desktop/dist/mas-universal-x64-temp/Electron.app/Contents/Resources/app.asar.unpacked/html-dist/xdcs/maps.xdc'  failedTask=build stackTrace=Error: EEXIST: file already exists, link '/Users/runner/work/deltachat-desktop/deltachat-desktop/html-dist/xdcs/maps.xdc' -> '/Users/runner/work/deltachat-desktop/deltachat-desktop/dist/mas-universal-x64-temp/Electron.app/Contents/Resources/app.asar.unpacked/html-dist/xdcs/maps.xdc'
    at link (node:internal/fs/promises:1052:10)
    at FileCopier.copy (/Users/runner/work/deltachat-desktop/deltachat-desktop/node_modules/builder-util/src/fs.ts:247:5)
```

**Comment by Simon-Laux** [comment]
ok, electron builder really does strange things here. I'm not willing to debug it as electron builder is a complex project. doing the copy in our afterPack hook instead of telling electron-builder to do it, has fixed the CI issue

**Review by Simon-Laux — APPROVED** [review]

**Pull request merged**
