### PR TITLE
Optimzing images

### PR DESCRIPTION
**Pull request by farooqkz**
I've optimized some of the images to reduce their size.

### CODE REVIEW

**Review by WofWca — COMMENTED** [review]
I guess it's fine, but IDK, they look rough, e.g. the checkmark's checkmark is not made out of straight lines. Maybe it's better to re-generate them from sources (SVG) with higher compression.
Oh, I just noticed that it's only used in "help". Well, the tray icon is rough still. I don't know how it looks on iOS.

Also `README_ASSETS/screenshot.png` is misisng.

Also this branch is not based on `main`.

**Review by Simon-Laux — CHANGES_REQUESTED** [review]
- dirty commit history, contains stuff from react pr
- some svg images look worse on first glance

what kind of optimisation did you use? lossy or lossless?

**Comment by Simon-Laux** [comment]
I'm also not sure about additional lossy (looks like detail is lost) compression on theocrat  bg image.

**Review by r10s — CHANGES_REQUESTED** [review]
there are lots of degradations not worth the few kb saved, esp. when looking at an appsize of 100-200 mb.

it is very obvious at the "guaranteed encrpytion" image, pixelized, wrong colors. but also tray logo and others are much worse.

is suggest to close this PR unmerged. one can do another attempt using eg. `oxipng -Z`

Screenshot 2024-06-19 at 23 14 19

**Pull request closed without merging**
