### PR TITLE
fix: a11y: wrong positioning of context menus

### PR DESCRIPTION
**Pull request by WofWca**
...when activating them with keyboard (or via other means?).

Closes https://github.com/deltachat/deltachat-desktop/issues/4244.

Some of the affected places:
- Three-dot button besides a message.
- Reactions bar when activated from the message context menu.
- "More options" in the QR reader dialog.
- "Appearance" settings color picker
    (it is not yet keyboard-accessible though).

### CODE REVIEW

**Comment by nicodh** [comment]
How can I test this? For me (on Linux) Ctrl + F10 works as shortcut to open the context menu in Chrome browser, but not in DC Desktop ?

**Comment by WofWca** [comment]
Weird. We use the native `contextmenu` event, so IDK. Maybe try the "context menu" button (to the right of the right Alt), if it's on your keyboard.

But for the places that I mentioned you don't really require it. You can open the three-dot menu with spacebar if you navigate to it by pressing Tab. Same for activating the "React" menu item (with Enter). Same with the gear icon in the QR scanner.

**Review by nicodh — APPROVED** [review]
Reviewed by testing

**Comment by WofWca** [comment]
This can be postponed until the next release, keyboard accessibility is not great anyway right now.

**Pull request merged**
