### PR TITLE
adding french translation of inAppHelp

### PR DESCRIPTION
**Pull request by eerielili**
Hello, here's a french translation of the help page.

### CODE REVIEW

**Comment by Simon-Laux** [comment]
thanks, but these pages are generated by https://github.com/deltachat/deltachat-pages/blob/master/tools/create-local-help.py, which uses the translations from transifex.
so doing it manually will be overwritten in the future.

**Comment by eerielili** [comment]
Okay, I'm switching to transifex right now :)

**Comment by Simon-Laux** [comment]
feel free to notify me when your done, then I can trigger the script.

**Comment by r10s** [comment]
> Okay, I'm switching to transifex right now :)

yeah, having a french help would be great!
current help is https://delta.chat/fr/help which is created from transifex and is translated only partly yet.

once the translation is mostly complete it will  go to andoid/ios/desktop.

**Comment by eerielili** [comment]
> feel free to notify me when your done, then I can trigger the script. ^^

I've send a "Join team" request in the [transifex](https://www.transifex.com/delta-chat/delta-chat-pages/), is that what you meant?

**Comment by r10s** [comment]
> I've sent a "Join team" request in the transifex, is that what you meant?

yes, thanks a lot! i approved your request, you should now be able to translate to french.

**Comment by eerielili** [comment]
I don't know if it's the right place to point this but,

[The RFC about the protected "Subjet" headers is _expired_](https://datatracker.ietf.org/doc/draft-autocrypt-lamps-protected-headers/). It does mean it won't get implemented or the
IETF has filled a better or more up-to-date RFC ?

The third bullet point in the _"How does Delta Chat protect my Metadata?"_ section mentions it.

**Comment by Simon-Laux** [comment]
superseded by #2227

@eerielili thank you for your help in making DeltaChat better!

**Pull request closed without merging**
