### PR TITLE
Remove BP dep from Gallery

### PR DESCRIPTION
**Pull request by farooqkz**
This PR aims to make Gallary working without BluePrintJs. Also refactors are done as needed.

### CODE REVIEW

**Comment by nicodh** [comment]
How is this related to #4006 ? Should it be merged together?

**Comment by farooqkz** [comment]
> How is this related to #4006 ? Should it be merged together?

This PR should be merged first.

**Comment by nicodh** [comment]
I moved the changes to https://github.com/deltachat/deltachat-desktop/tree/gallery-remove-bp

We should not introduce new feature together with the blue print removal and the refactoring.

The branch is not working, several errors in the gallery views (Videos and other)

**Comment by farooqkz** [comment]
> I moved the changes to https://github.com/deltachat/deltachat-desktop/tree/gallery-remove-bp

Okay 
> We should not introduce new feature together with the blue print removal and the refactoring.


I didn't.

> The branch is not working, several errors in the gallery views (Videos and other)

Of course it's not finished yet.

**Pull request closed without merging**
