### PR TITLE
Move create verified group button to the right and add some margin

### PR DESCRIPTION
**Pull request by Jikstra**
this still misses:
- [x] pulling in new translations which add the (experimental) thing

I don't have the transiflex client installed and don't know shit about this, @ralphtheninja can you help me out with pulling in the translations?

Will fix https://github.com/deltachat/deltachat-desktop/issues/523

### CODE REVIEW

**Comment by ralphtheninja** [comment]
As I said here https://github.com/deltachat/deltachat-desktop/issues/523#issuecomment-455183323 I don't get an update of `en.xml` when doing `tx pull --all`.

**Comment by Jikstra** [comment]
@r10s any ideas why we don't get the new translations?

**Comment by r10s** [comment]
not sure what exactly `--all` does, on android, we're using `tx pull -l en`, see script at https://github.com/deltachat/deltachat-android/blob/master/tools/tx-pull-source.sh

**Comment by ralphtheninja** [comment]
> not sure what exactly `--all` does, on android, we're using `tx pull -l en`, see script at https://github.com/deltachat/deltachat-android/blob/master/tools/tx-pull-source.sh

That did the trick!

**Pull request merged**
