### PR TITLE
perf: fix low FPS on chat scroll on some machines (again)

### PR DESCRIPTION
**Pull request by WofWca**
- [x] This is based on #3743, expecting that to get merged first

Before:
image

After:
image

### CODE REVIEW

**Comment by WofWca** [comment]
Hold up, this increases scripting time significantly. Will try to optimize now.

**Comment by WofWca** [comment]
> Hold up, this increases scripting time significantly. Will try to optimize now.

Ok, fixed. I didn't know React re-renders on all `setState`s and not just the ones that can actually affect DOM.

**Comment by WofWca** [comment]
Ehh, I'm not sure about whether we should actually turn it off on timeout. Because if you stop for >3 seconds, then scroll again, there will be a stutter.
Maybe only enabling `will-change` when we're scrolled all the way bottom makes more sense?

But this is better than it is now anyways, so it can be merged IMO.

**Review by adzialocha — APPROVED** [review]
Great work! 🕵🏻 

I can't "see" or test the differences as my available machines are too fast, but the code looks good.

**Review by Simon-Laux — APPROVED** [review]
I have a bad feeling with the timeout, we need to pay attention to it. But let's merge for now and see how it goes.

We can disable the switching logic for high-dpi screens in a follow-up pr, because there you can not see the blurriness anyway

**Comment by farooqkz** [comment]
Nice job there! I was supposed to test these performance issues on me le potato.

**Comment by WofWca** [comment]
I just found out that we're also using `will-change` for the chat list:

https://github.com/deltachat/deltachat-desktop/blob/cdf2b7fccaa2f964297a4610fbafdcad266fdebd/src/renderer/components/chat/ChatList.tsx#L84

https://github.com/bvaughn/react-window/commit/98b6e3da51c4c4348ce1074920784f08b97e8b21

**Pull request merged**
