### PR TITLE
networked multidevice setup

### PR DESCRIPTION
**Pull request by Simon-Laux**
- [x] receiving
- [X] sending
- [x] remove timeout hack
- [x] translation keys
- [X] troubleshooting link
- [x] adjust that it looks like on android
   - [ ] ~~receive~~ postponed, is good enough for now
   - [X] send
- [x] set new core string
- [x] some kind of success feedback on sending 

depends on new core with these prs merged:
- https://github.com/deltachat/deltachat-core-rust/pull/4007
- https://github.com/deltachat/deltachat-core-rust/pull/4198

### CODE REVIEW

**Comment by Simon-Laux** [comment]
problem is that there is a progress-bar / it takes a while until the qr code is returned by core

**Comment by hpk42** [comment]
"hash mismatch" error with Android 1.36.0 scanning a QR procuced from this branch + core stable-1.112 as of 20 minutes ago 
image
i don't get this hash mismatch when using two Anroid 1.36.0's devices.

**Comment by hpk42** [comment]
just to note down here as well: it seems that my original problem 
can be traced back to an iroh issue with 30-40K files in the collection -- 
@flub was able to quite reliably reproduce it in a test.

**Comment by meganoahj** [comment]
So I tried using the repl tool to test out the new transfer backup locally function from and to Windows, which only worked after disabling the windows firewall manually (could be because Delta Chat is an untrusted app and Windows blocks every non standard port or protocol?) after some research I found out that there are multiple ways to fix this issue.

I tried it on windows 11 but it should be the same from windows 7 and up because they all still use nt firewall.

The simplest fix at least in my perspective would be using batch file creating firewall rule (could be integrated into installer) see here: https://www.itninja.com/blog/view/allow-an-app-through-firewall

I created an example batch file (needs admin access) which should work on every supported winver because it uses nt commands:

dcfix.bat
`netsh advfirewall firewall add rule name="DC in" profile=domain,private,public protocol=any enable=yes DIR=In program="C:\Users\Noah\Projects\deltachat-core-rust\target\debug\deltachat-repl.exe" Action=Allow
netsh advfirewall firewall add rule name="DC out" profile=domain,private,public protocol=any enable=yes DIR=Out program="C:\Users\Noah\Projects\deltachat-core-rust\target\debug\deltachat-repl.exe" Action=Allow`


Other ways could be using a firewall api to create the rules (prob have to rewrite because of way too much code or the smaller one also using c++)

https://github.com/microsoft/windows-rs (Official Microsoft Rust API)
https://github.com/marirs/winfw-rs (Smaller Bootleg firewall only API)

**Comment by flub** [comment]
Directly creating holes in the windows firewall using their API sounds interesting.  Is there any documentation from microsoft on what you're allowed to do there?  Are there any permissions to deal with?

**Pull request merged**
