### PR TITLE
Submission to mac appstore

### LINKED ISSUE #1528: publish version on macOS store
we should definitely have the desktop version in the macOS store :)

### LINKED ISSUE #1607: Mac builds are not notarized
Screen Shot 2020-05-05 at 22 31 14

https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db

### PR DESCRIPTION
**Pull request by Simon-Laux**
Problems we need to fix:
- [X] AppIcon
- [x] ITMS-90296: App sandbox not enabled
- [x] ITMS-90237: The product archive package's signature is invalid. Ensure that it is signed with your "3rd Party Mac Developer Installer" certificate.

- [X] DMG notarized and running
- [x] Mac appstore version sandboxed and running (it crashes on startup with no message)

- [x] fix dev build (the switch to electron-builder.yml broke it)

- [x] todo rebase

- [x] fix mapbox css missing

- [x] screenshot and submit imaginary 1.4.1 pre-release version to test whether we pass the review process

https://github.com/deltachat/deltachat-desktop/issues/1136#issuecomment-605454589

closes #1528 
closes #1607

### CODE REVIEW

**Comment by Jikstra** [comment]
How did you test that the crash happend?
Did you build the .dmg (or .pkg or what it is?) and try to start it?

**Comment by Simon-Laux** [comment]
I build the pkg thingie, installed it and tried to start it.

**Comment by Simon-Laux** [comment]
side note of the side-quest of this pr (saving space in package):
electron-builder is seemingly unable to exclude a npm package while only keeping a few files of it.

**Comment by Simon-Laux** [comment]
looks like https://gist.github.com/salomvary/c8728f97d3ae916ea11129ebadf8b85f did the trick

**Pull request merged**
