### PR TITLE
Implement emoji picker 

### PR DESCRIPTION
**Pull request by Jikstra**
Still needs:
- [x] Some css/js to show/hide the picker above the other elements
- [x] Actually input the emoji into the chat input
- [x] inclue the emoji packs somehow/use the right ones, currently we load them from unpkg (not good)
- [x] use onMouseOver above the emoji icon to show the picker, when it's outside of picker/button hide it again
- [x] Use better emoji icon/readjust icons in composer

Fixes https://github.com/deltachat/deltachat-desktop/issues/475

screenshot_20190123_004501

### CODE REVIEW

**Comment by Simon-Laux** [comment]
@Jikstra make sure the font is used in the picker(to don't increase our package size too much) and it shouldn't download anything from any cdn (As far as I understood the emojimart readme, using a cdn is enabled by default)

**Comment by Jikstra** [comment]
`emoji-mart` isn't using any font, it's always using images for every emoji. How to proceed? @Simon-Laux
I'm not sure but to me it seems like using images for emojis is the way to go?

**Comment by Simon-Laux** [comment]
emoji_disaligned
Maybe thats font specific, it was probably needed by the images.

**Comment by Simon-Laux** [comment]
Picker gets bigger, when width gets smaller and blocks the view:
<details> <summary>Show Screenshots</summary>

s1
s2

</details>

**Comment by Simon-Laux** [comment]
The Icons for attachment/ emoji are too small/ too far apart. It looks a bit odd IMO

- [ ] Check when fixed

Also I think using this heart as icon/symbol could be confusing, I would prefer some face emoji. To make it more interesting we could switch to a different face emoji every time the cursor passes by like discord did it.
- [ ] Check when fixed / resolved / discussed

**Comment by Jikstra** [comment]
> Also I think using this heart as icon/symbol could be confusing, I would prefer some face emoji. To make it more interesting we could switch to a different face emoji every time the cursor passes by like discor

It's changed. There was a wip tag for a reason :P But I appreciate it that you're hungry for this feature ^^ Most of the other points are still open ^^

**Comment by Jikstra** [comment]
> Picker gets bigger, when width gets smaller and blocks the view:

I did this for a reason as it's otherwise too small. I think it's fine to use more of the width when being smaller so that you can still select them. You normally don't want to read the messages while picking an emoji.

**Comment by ralphtheninja** [comment]
> I would prefer to merge this asap, minor things we can fix/improve later.

Yeah, lets rebase and merge it and take it from there.

**Comment by ralphtheninja** [comment]
I'm solving the conflict by merging master into this branch for now.

**Comment by Simon-Laux** [comment]
Yeah lets merge this ASAP and do an Issue for the other points.
Great Job, LGTM (I just user-tested it, I can't say anything about the code.)

**Comment by r10s** [comment]
looks great :)

**Comment by ralphtheninja** [comment]
No wtf. The whole logger code is reverted in this PR.

@Jikstra What have you done? :)

**Pull request closed without merging**
