### PR TITLE
Change archive back icon

### PR DESCRIPTION
**Pull request by nicodh**
resolve #4148

### CODE REVIEW

**Review by WofWca — APPROVED** [review]
image

**Review by r10s — COMMENTED** [review]
very nice to push that forward! that will be a big usability improvement!

currently, only the color is wrong - this is visible also in dark mode, but even more in light mode:

Screenshot 2024-10-16 at 11 07 41

the arrow should just get the color of the text. this would also improve the display in settings (where `<backButton>` probably comes from), where the grey looks a bit disabled, just using text color would also better there

**Comment by nicodh** [comment]
Icon color is now the same as text color

**Comment by r10s** [comment]
> Icon color is now the same as text color

it picks up body text color, but not title bar text color 😅 (which are maybe same in dark mode, but not in lite mode)

Screenshot 2024-10-16 at 16 35 44

**Comment by nicodh** [comment]
> > Icon color is now the same as text color
> 
> it picks up body-text-color, but not title-bar-text-color 😅 (which are maybe same in dark mode, but not in lite mode) 
> (sorry if i have been unclear above)

Oh my gosh! Sorry is on my side! - I only checked it in the settings dialog, so it seems we have to declare a special prop to differentiate if we are on a dialog header or a navbar.

Seems too easy...
I will have a look tomorrow

**Comment by nicodh** [comment]
> i just noticed, that we have the arrow already in the correct layout when the chatlist is hidden:
> maybe better reuse that?

where is that?

**Comment by nicodh** [comment]
I now reuse the back button from small screen

No idea why it was not used also on default screen size before

**Review by r10s — APPROVED** [review]
very nice!

cannot say much to the css, but it works and looks as expected now :)

**Review by Simon-Laux — APPROVED** [review]

**Pull request merged**
