### PR TITLE
Improve styling of help pages

### PR DESCRIPTION
**Pull request by Jikstra**
Before:
grafik

After:
grafik

### CODE REVIEW

**Comment by r10s** [comment]
is the hint to the online FAQ page really that important that it requires a permanent hint?

tbh, i would just remove it. there is the link "learn more about Delta Chat" that opens the homepage in the main menu. and, if we really think, we need some kind of "this is a copy from ...", we can just add it to the page, this way, we would have it also on all systems. but i do not think it is needed at all.

**Comment by pabzm** [comment]
> is the hint to the online FAQ page really that important that it requires a permanent hint?

It's not, this is just what we discussed (as of my holey mind). I like the hint, but I don't find it important, so go ahead.

**Comment by Jikstra** [comment]
@Simon-Laux can't reproduce:
grafik

**Pull request closed without merging**
