### PR TITLE
Mute Chat

### LINKED ISSUE #1455: Mute Chat
Ability to mute a chat.

Progress:
- [x] core api (still has a bug)
- [x] dc-node part (https://github.com/deltachat/deltachat-node/pull/446)
- [ ] Desktop part

Notes:
- maybe copy ui from ephemeral messages?

### PR DESCRIPTION
**Pull request by Simon-Laux**
- [X] indicator icon for muted chats
- [X] mute a chat
- [x] notifications are ignored for muted chats (needs testing)
- [x] select a mute duration instead of muting forever
- [x] require deltachat-node with https://github.com/deltachat/deltachat-node/pull/446 merged
- [ ] require a deltachat node that links to a core which has the bug that you can only mute groups fixed (https://github.com/deltachat/deltachat-core-rust/pull/1470)

closes #1455

### CODE REVIEW

**Comment by Jikstra** [comment]
can you change the `"deltachat-node": "git+https://github.com/deltachat/deltachat-node.git#mute-chat"` thing in package.json?

> require a deltachat node that links to a core which has the bug that you can only mute groups fixed (deltachat/deltachat-core-rust#1470)

Let's not wait for this if it takes too long to get merged

I can help you with ui/ux thingies for selecting the mute duration

**Comment by Simon-Laux** [comment]
> I can help you with ui/ux thingies for selecting the mute duration

sure if you want you may continue this pr.

**Comment by Simon-Laux** [comment]
notification muting works now.
I just wonder why @Jikstra renamed `shared/shared-types` to `shared/shared-types.d `. That makes this pr bigger and thus harder to review.

**Comment by Jikstra** [comment]
Because I put the enum containing the MuteDuration timer into the shared-types.ts file (which didn't exist before). Putting it into the shared-types.d.ts didn't work, seems like it's not allowed to have actual value initializations in a .d.ts.

**Comment by Jikstra** [comment]
@Simon-Laux anything missing? Otherwise lets get it merged :)

**Comment by Simon-Laux** [comment]
We still need to link a new core that has muting of DM chats fixed, but besides that we can merge it

**Comment by Jikstra** [comment]
Oh we didn't forewardport the update deltachat-node thingy... Yeah who cares, can do that afterwards.

**Pull request merged**
