### PR TITLE
fix message rendering new line behaviour

### LINKED ISSUE #1119: empty lines are not preserved
separating paragraphs using an empty line does not work, multiple linefeeds seems to be converted to a single one.

```
this is a paragraph.

and this another.
```

is converted to
```
this is a paragraph.
and this another.
```

i think it is okay to convert >2 linefeeds to 2 linefeeds, but 1 or two linefeeds should be allowed.

### PR DESCRIPTION
**Pull request by Simon-Laux**
fixes #1119

### CODE REVIEW

**Comment by Simon-Laux** [comment]
I would like to move the message parser (markdown and links) to the core. But I'll need to learn how to code parsers in rust first.

**Comment by hpk42** [comment]
On Wed, Nov 06, 2019 at 14:53 -0800, Simon Laux wrote:
> I would like to move the message parser (markdown and links) to the core. But I'll need to learn how to code parsers in rust first.

pretty sure there is a crate for parsing markdown ;)

**Comment by Simon-Laux** [comment]
We'll have our own flavor of markdown, so I believe it makes sense to do it from scratch. Also for the learning experience.

**Comment by Jikstra** [comment]
Please give it a try for learning experience, but our markdown flavour isn't that much different, and if so, i would prefer to drop that and stay with standard markdown.

**Comment by Jikstra** [comment]
But links are supported in markdown? If only mentions is the problem, we can hack around that without writing our own markdown parser (which is probably not as easy to get it properly working, especially if you never did that. Still a very good thing to try and a good side project).

**Comment by Simon-Laux** [comment]
links with `[description](link)` we won't and shouldn't support (security for average users).
In essence its a custom flavor of markdown. Also as I wrote, we need a special AST format, html won't do it, because we want to use it in iOS and android too. Anyways that markdown parser isn't too important right now. I'll work on #1123 first, before starting the message parser.

**Pull request merged**
