### PR TITLE
blueprintjs removal part1

### PR DESCRIPTION
**Pull request by maxphilippov**
- replace all occurrences of BlueprintJS Icon, Button, Radio, RadioGroup, Collapse components

#3811 approval is required to merge this

### CODE REVIEW

**Comment by hpk42** [comment]
this is not meant for inclusion for 1.46 release, is it?

**Comment by farooqkz** [comment]
What is status of this? Ready for review?

**Comment by maxphilippov** [comment]
> What is status of this? Ready for review?

I'll push today-tomorrow an updated version, maybe as a separate pr, I didn't touch the Gallery, but removed everything else (including dependency from package.json, so you could probably test your changes against my branch)

**Comment by farooqkz** [comment]
> > What is status of this? Ready for review?
> 
> I'll push today-tomorrow an updated version, maybe as a separate pr, I didn't touch the Gallery, but removed everything else (including dependency from package.json, so you could probably test your changes against my branch)

Not touching Gallery is alright as I have another PR for that.

**Comment by maxphilippov** [comment]
Closing this one in favor of a more complete effort: #4006

**Pull request closed without merging**
