### PR TITLE
solve problem of exceptions on quit. fix #2201

### LINKED ISSUE #2201: Uncaught exception after quitting
- Operating System (Linux/Mac/Windows/iOS/Android):
Windows 8.1 Pro.

- Delta Chat Version:
1.15.5/1.33.2.

- Expected behavior:
Delta Chat does not crash (uncaught exception) after quitting.

- Actual behavior:
Delta Chat crashes (uncaught exception) after quitting.

- Steps to reproduce the problem:
Unfortunately I cannot reproduce the issue.

- Screenshots:
DC_uncaught exception

- Logs:
[DC_uncaught_exception.txt](https://github.com/deltachat/deltachat-desktop/files/6231073/DC_uncaught_exception.txt)

### PR DESCRIPTION
**Pull request by farooqkz**
This fixes #2201

### CODE REVIEW

**Review by Simon-Laux — APPROVED** [review]
code lgtm, did not test it though

**Comment by farooqkz** [comment]
@Simon-Laux  @gerryfrancis Merge?

**Comment by Simon-Laux** [comment]
you can merge it after a rebase

**Comment by farooqkz** [comment]
> you can merge it after a rebase

after several tries and force push, I noticed a rebase is not needed :)

**Pull request merged**
