### PR TITLE
Lazy-load contacts

### PR DESCRIPTION
**Pull request by WofWca**
It's easier to review the changes commit-by-commit (also I'd prefer "rebase and merge" instead of "squash"). Also, for the last commit, GitHub is not good at showing whitespace-only changes, which it mostly is.
I did a bit of QA (but maybe not enough), and looked at the code. It doesn't look like anything should break.

TODO:
- [x] There are 2 more places where `<InfiniteLoader>` needs to be added. For now I just want to show the general approach and see if anyone has objections to it.
- [x] Now the only problem is `Invalid list ref; please refer to InfiniteLoader documentation.` in the console. I think we might need to set it on `<AutoSizer` instead? not sure. Should not be a blocker for reviews. Update: solved by putting `<FixedSizeList` as a direct child of `<InfiniteLoader`

### CODE REVIEW

**Comment by Simon-Laux** [comment]
no objections so far.

**Comment by farooqkz** [comment]
Is this PR ready for review? If yes, why is it a draft?

**Comment by WofWca** [comment]
No, not ready. Draft because it's not done yet. Need to clean up, and change a few more places.

**Comment by farooqkz** [comment]
> No, not ready. Draft because it's not done yet. Need to clean up, and change a few more places.

Alright. Looking forward to it!

**Review by Simon-Laux — APPROVED** [review]

**Pull request merged**
