### PR TITLE
simon/adapt to instant onboarding changes

### LINKED ISSUE #3833: adapt to last-minute instant-onboarding changes
https://github.com/deltachat/deltachat-android/pull/3060, https://github.com/deltachat/deltachat-android/pull/3064, https://github.com/deltachat/deltachat-android/pull/3068 are the outcome of one-to-one discussions during the current gathering; see there fore reasoning and discussion.

in summary, the following changes are needed in onboarding:

- [x] pull translations
- [x] create a regular secondary button with the string **Use Other Server** (`instant_onboarding_show_more_instances`) below "Agree & Create Profile"
- [x] on tapping **Use Other Server**, an dialog (same as for "I already have a login") with the following options should open:
    - **List Chatmail Servers** (`instant_onboarding_other_server`) - do the same as "Explore Other Options" before
    - **Classic E-Mail Login** (`manual_account_setup_option`) - do the same as "I Already Have A Login / Manual Login" before
    - **Scan Invitation Code** (`scan_invitation_code`) - do the same a "Scan QR Code" before
- [x] remove the lower two buttons "Explore Other Options" and "Scan QR Code"
- [x] remove  "I Already Have A Login / Manual Login" (options left are "Add as Second Device" and "Restore From Backup")

the following changes are needed in "New Chat":

- [x] rename "Scan QR Code" to **New Contact** (`menu_new_contact`) and move it up
- [x] if `isChatmail()` is `true`, the placeholder must no longer read "Enter name or e-mail address" but just **Search** (`search`)
- [x] if an email address is entered, rename "New Contact" to **Add Contact Manually** (`menu_new_classic_contact`) 

(showing it unconditional to `isChatmail()` seems to be the easiest option, gist is that when `isChatmail()` is `true`, there is no easy path to enter an email address (alternatives would be https://github.com/deltachat/deltachat-android/pull/3064 , but that would require a menu in the "QR Code" dialog and may be harder)

in manual contact adding activity:

- [ ] use the title **Add Contact Manually** (`menu_new_classic_contact`)
- [ ] add the hint `new_classic_contact_explain` below the input fields

### LINKED ISSUE #3838: the title on adding subsequent profiles should read "Add Profile", not "Welcome"
when adding additional profiles using the "+" button on the sidebar, the title should read "Add Profile" (`add_account`).

only on the very first start, if there is no profile yet, it should read "Welcome to Delta Chat" (`welcome_desktop`)

this was correct in 1.44, but it current master always displays "Welcome to Delta Chat" which does not make much sense in case ppl are maybe using Delta Chat for a long time already and just want to add another profile, also "Add Profile" has much more about what is happening

### PR DESCRIPTION
**Pull request by Simon-Laux**
- **change title of welcome screen according to `the title on adding subsequent profiles should read "Add Profile", not "Welcome"`**
- **welcome screen make sure logo is shown also on smaller window sizes**
- **adapt to instant onboarding changes in onboarding**
- **rm option to manual login from "I Already Have A Login"**
- **rename "Scan QR Code" to New Contact (menu_new_contact) and move it up**
- **if isChatmail() is true, the placeholder must no longer read "Enter name or e-mail address" but just Search (search)**
- **if an email address is entered, rename "New Contact" to Add Contact Manually (menu_new_classic_contact)**
- **fix condition**

closes #3833
closes #3838

### CODE REVIEW

**Review by r10s — COMMENTED** [review]
thanks a lot for the chances! did a quick functionality check:

- the title of the "User Other Server"-_dialog_ should read "User Other Server"

- the "User Other Server"-_dialog_ should close when tapping "List Chatmail Server" - for "Scan Invitation Code", this is already done

- the "Use Other Server"-_button_ should not disappear even if another servers was chosen; ppl may change their mind

- with the primary button disabled, the secondary button looks like ppl will just try to hit them, when not reading things. also the "error pointer" looks a bit too much as if things already went wrong. instead of tweaking UI wise, maybe go the android way and always have the button enabled - but if no name is set, show a toast or another warning (this is btw also the desktop way elsewhere, eg "New Group")

moreover, set name+avatar should be used also when go for "Use Other Server / Classic E-Mail Login". however, if that's tricky, we can postpone it and do it in a subsequent PR

**Comment by Simon-Laux** [comment]
> the "Use Other Server"-button should not disappear even if another servers was chosen; ppl may change their mind

they can always go back, but sure if you say so we do that

**Comment by Simon-Laux** [comment]
> moreover, set name+avatar should be used also when go for "Use Other Server / Classic E-Mail Login". however, if that's tricky, we can postpone it and do it in a subsequent PR (https://github.com/deltachat/deltachat-android/issues/3080)

https://github.com/deltachat/deltachat-desktop/pull/3850

**Review by r10s — APPROVED** [review]
tested again, looks good to me now, thanks a lot!

**Pull request merged**
