### PR TITLE
🚧 Mocha integration tests

### PR DESCRIPTION
**Pull request by nicodh**
NEW! Now with dynamic account creation

### CODE REVIEW

**Comment by Jikstra** [comment]
I guess the tests for the faq need to get ported to mocha too? @pabzm

**Comment by pabzm** [comment]
> I guess the tests for the faq need to get ported to mocha too?

True. They are not run by default anyway (using `tape` at least), so I'd wait for this PR to finish, and then change them.

**Comment by Jikstra** [comment]
Wow. With have green ci tests? What magic did you do? :D

**Comment by Jikstra** [comment]
So I was playing around with cpulimit. It's a tool to more or less make a process slower by interrupting it more often, and with this tool i can reproduce the `waitUntilTextExists Promise was rejected with the following reason: timeout` error.

```
$ cpulimit -l 25 -i npm run test-integration

> deltachat-desktop@0.901.0 test-integration /home/kerle/Workspace/deltachat-desktop
> mocha "./test/integration/index.js"



  Login with false mail address gives an error
    ✓ app runs
    ✓ wrong credentials results in error message (1084ms)

  Login with valid credentials works
    1) login with valid credentials


  2 passing (58s)
  1 failing

  1) Login with valid credentials works
       login with valid credentials:
     waitUntilTextExists Promise was rejected with the following reason: timeout
  Error: Promise was rejected with the following reason: timeout
      at new WaitUntilTimeoutError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:149:12)
      at /home/kerle/Workspace/deltachat-desktop/node_modules/webdriverio/build/lib/commands/waitUntil.js:36:15



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deltachat-desktop@0.901.0 test-integration: `mocha "./test/integration/index.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deltachat-desktop@0.901.0 test-integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kerle/.npm/_logs/2020-01-19T21_06_44_557Z-debug.log

```

**Comment by Jikstra** [comment]
So I was playing around with cpulimit. It's a tool to more or less make a process slower by interrupting it more often, and with this tool i can reproduce the `waitUntilTextExists Promise was rejected with the following reason: timeout` error.

```
$ cpulimit -l 25 -i npm run test-integration

> deltachat-desktop@0.901.0 test-integration /home/kerle/Workspace/deltachat-desktop
> mocha "./test/integration/index.js"



  Login with false mail address gives an error
    ✓ app runs
    ✓ wrong credentials results in error message (1084ms)

  Login with valid credentials works
    1) login with valid credentials


  2 passing (58s)
  1 failing

  1) Login with valid credentials works
       login with valid credentials:
     waitUntilTextExists Promise was rejected with the following reason: timeout
  Error: Promise was rejected with the following reason: timeout
      at new WaitUntilTimeoutError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:149:12)
      at /home/kerle/Workspace/deltachat-desktop/node_modules/webdriverio/build/lib/commands/waitUntil.js:36:15



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deltachat-desktop@0.901.0 test-integration: `mocha "./test/integration/index.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deltachat-desktop@0.901.0 test-integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kerle/.npm/_logs/2020-01-19T21_06_44_557Z-debug.log

```

**Comment by nicodh** [comment]
So that might be the reason why it fails on CI...

**Comment by Simon-Laux** [comment]
We should increase the standard time out for the tests, I would say to a number that 1-2 seconds is still green and not already yellow.

Also the run test-integration-local fails for me:
<details>
<summary>Show</summary>
```
$ npm run test-integration-local

> deltachat-desktop@0.901.0 test-integration-local /home/simon/Documents/Projects/dcd-debug-env/deltachat-desktop
> mocha "./test/integration/local.js"



  Login with false mail address gives an error
    ✓ app runs
    ✓ wrong credentials results in error message (1021ms)

  Login with valid credentials works
    ✓ login with valid credentials (11502ms)

  Login with other valid credentials works
    ✓ login with valid other credentials (11629ms)

  Accounts are created
    ✓ accounts are created (1339ms)

  Create chat and send message works
    ✓ create chat (4252ms)
    ✓ send message (2481ms)

  Contact request and receive message works
    1) "before all" hook: async for "contact request is displayed"

  Update and persist Desktop settings
    2) "before all" hook: async for "changing a settings is applied to config.json"


  7 passing (1m)
  2 failing

  1) Contact request and receive message works
       "before all" hook: async for "contact request is displayed":
     waitUntilWindowLoaded Cannot read property 'isLoading' of undefined
  TypeError: Cannot read property 'isLoading' of undefined
      at Object.<anonymous> (node_modules/spectron/lib/application.js:244:31)
      at Timer.tick (node_modules/webdriverio/build/lib/utils/Timer.js:111:31)
      at Timer.start (node_modules/webdriverio/build/lib/utils/Timer.js:75:22)
      at new Timer (node_modules/webdriverio/build/lib/utils/Timer.js:62:14)
      at Object.exports.default (node_modules/webdriverio/build/lib/commands/waitUntil.js:25:17)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:190:29)
      at /home/simon/Documents/Projects/dcd-debug-env/deltachat-desktop/node_modules/webdriverio/build/lib/webdriverio.js:485:32
      at _fulfilled (node_modules/q/q.js:854:54)
      at /home/simon/Documents/Projects/dcd-debug-env/deltachat-desktop/node_modules/q/q.js:883:30
      at Promise.promise.promiseDispatch (node_modules/q/q.js:816:13)
      at /home/simon/Documents/Projects/dcd-debug-env/deltachat-desktop/node_modules/q/q.js:570:49
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at processTicksAndRejections (internal/process/task_queues.js:75:11)

  2) Update and persist Desktop settings
       "before all" hook: async for "changing a settings is applied to config.json":
     Client initialization failed after 10 attempts: RuntimeError Client initialization failed after 10 attempts: 
  Error: unknown error: Chrome failed to start: exited abnormally
    (chrome not reachable)
    (The process started from chrome location /home/simon/Documents/Projects/dcd-debug-env/deltachat-desktop/node_modules/spectron/lib/launcher.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    (Driver info: chromedriver=69.0.3497.106 (857b284701ddf7bef0f14fa76416cf7ca786b411),platform=Linux 4.19.96-1-MANJARO x86_64)
      at new RuntimeError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
      at Request._callback (node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:476:20)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:476:20)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at IncomingMessage.EventEmitter.emit (domain.js:476:20)
      at endReadableNT (_stream_readable.js:1183:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
</details>

**Comment by nicodh** [comment]
So we have a "reproducable random behaviour" :-(

**Comment by Simon-Laux** [comment]
the test cafe thing is wip and @Jikstra wants to improve something in this pr, so I added the 🚧 wip status.

**Pull request closed without merging**
