### PR TITLE
Only show advanced settings the user entered

### PR DESCRIPTION
**Pull request by nicodh**
relates #1121

First step of reworking the advanced settings. Taking https://github.com/deltachat/deltachat-android/issues/1106#issuecomment-550467772 into account.

In current master the configured: prefixed values are displayed instead of the manually entered values.

### CODE REVIEW

**Comment by nicodh** [comment]
Although there is no distinction between placeholder and label in material design I made a difference to show the user what kind of default values are used.

**Comment by nicodh** [comment]
new-advanced-settings

**Comment by nicodh** [comment]
Very strange: CI fails because of a console.log statement in a non existing file: src/renderer/components/dialog/ViewProfile.js ???

**Comment by link2xt** [comment]
> Very strange: CI fails because of a console.log statement in a non existing file: src/renderer/components/dialog/ViewProfile.js ???

But the file does exist: https://github.com/deltachat/deltachat-desktop/blob/master/src/renderer/components/dialogs/ViewProfile.js

Maybe you have deleted it locally?

**Comment by nicodh** [comment]
Yes it exists in master, but it didn't  in this branch before the last merge with master

**Pull request merged**
