### PR TITLE
[0] Implement Stickers, rework emoji picker, refactor folder structure

### PR DESCRIPTION
**Pull request by Jikstra**
- Reworks emoji picker and implements stickers
  - For testing you can send any telegram sticker pack to the @Stickerdownloadbot, download the png version and unpack it's *.png files into `~/.config/DeltaChat/<yourid>/stickers/<somestickerpackname>`.
- Refactors Composer, changes onMouseHover behaviour to 'you need to click on emoji picker to open, click somewhere else to close'
- Applies a new and more sane folder structure to src/renderer and scss (one more part of moving styled components to sass). For example we now group components/scss by `message`, `chat`, `contact`...

### CODE REVIEW

**Comment by Simon-Laux** [comment]
Can you re-add the emoji searchbar? you can also 
And make the emoji category selector bigger?

**Comment by Simon-Laux** [comment]
what are those `.scss.kate-swp` files like `scss/._global.scss.kate-swp`?

**Comment by Jikstra** [comment]
> Can you re-add the emoji searchbar? And make the emoji category selector bigger?

Yup but not before we merged the other 2prs into this one.

**Comment by Jikstra** [comment]
This pr will make the messagelist a bit worse because we're not scrolling down anymore when we're reading a message. Didn't fix it yet because i would like to implement a new messagelist right away.

**Comment by Simon-Laux** [comment]
emoji search by text is useful, sometimes it is quicker to search via English text than looking for a specific emoji in all categories...

**Comment by r10s** [comment]
> emoji search by text is useful, sometimes it is quicker to search via English text than looking for a specific emoji in all categories...
Other apps do the search differently over : + searchterm in the composer than they show a popup of the reults where you can choose the right one.

yip, it is useful for some users sometimes.

but i would also regard that as a power-feature we can target later. for now, the search bar stands in our way while refactoring the emoji/sticker-picker, so we decided to remove it for now.

**Pull request merged**
