### PR TITLE
Remove inbox_watch and mvbox_watch and add only_fetch_mvbox

### PR DESCRIPTION
**Pull request by flipsimon**

### CODE REVIEW

**Comment by Simon-Laux** [comment]
There will be a new option for watch settings.
See https://github.com/deltachat/deltachat-core-rust/blob/master/CHANGELOG.md#1730

##### References
https://github.com/deltachat/deltachat-core-rust/pull/3028
https://support.delta.chat/t/schlechtes-handling-von-extentionsadressen/1990/15

Does desktop need anything else beside a new toggle switch for `only_fetch_mvbox`? @Hocuri @flub

**Comment by flub** [comment]
> [deltachat/deltachat-core-rust#3028](https://github.com/deltachat/deltachat-core-rust/pull/3028) https://support.delta.chat/t/schlechtes-handling-von-extentionsadressen/1990/15
> 
> Does desktop need anything else beside a new toggle switch for `only_fetch_mvbox`? @Hocuri @flub

No, only a new switch is needed.  The wording of it is the tricky part though.  @r10s said this, which I think is true:

> for the android part, i think, the option description should mention that that requires the help of the server, i think, that is the most important part of that option to explain, more important than the "Spam folder" bit.

**Comment by Hocuri** [comment]
>  The wording of it is the tricky part though

I'd just suggest using the same config name and description as Android does now.

**Comment by Simon-Laux** [comment]
https://github.com/deltachat/deltachat-android/pull/2206

**Comment by Jikstra** [comment]
@flipsimon can you rebase this/remove the unrelated commits of simon?

**Pull request merged**
