### PR TITLE
Add format image

### PR DESCRIPTION
**Pull request by ejgonzalez17**
**Solves #2491 (When selecting the image profile, it does not accept .jpeg .ico .apng format)**

**Description**
Add image formats in the process of selecting a new image in the profile

**Why**
When trying to select an image in the profile photo, formats such as .jpeg or .ico are not accepted.

**Additional information** 
Formats are added in Setting-Profile.tsx and in ViewGroup.tsx
Screen Shot 2022-01-06 at 4 21 25 PM

Screen Shot 2022-01-06 at 4 21 58 PM

### CODE REVIEW

**Comment by r10s** [comment]
adding `.jpeg`, should be fine. maybe also add `.jpe` at the same time, that is also used here and there for JPEG images.

for `.apng`, `.ico` and `.webp` - they should not be used for own profile images. the images are sent to other clients using other ui (android, ios) and it is not clear if all other ui support these formats or if core converts them to png/jpg (i suspect that).

**Comment by ejgonzalez17** [comment]
Okay , I'll change so that only .jpeg and .jpe are added .

**Comment by r10s** [comment]
@ejgonzalez17 thanks a lot for taking care!

**Review by Simon-Laux — CHANGES_REQUESTED** [review]
@ejgonzalez17 can you run `npm run fix-formatting` and mention your change in the `CHANGELOG.md` file?
Besides these 2 trivial points the PR looks good to me, thanks for contributing!

**Comment by ejgonzalez17** [comment]
Hi , sorry for the delay, I have already uploaded the marked changes , I am waiting for your corrections or comments.

**Comment by Jikstra** [comment]
> Hi , sorry for the delay, I have already uploaded the marked changes , I am waiting for your corrections or comments.

Looks good. I think it makes sense to move the image formats in constant array so that it can get reused and only needs changes at one place. Similiar to what @naomiceron did over here: https://github.com/deltachat/deltachat-desktop/pull/2488#discussion_r780772205

I will do this quickly after merging. Thank you :)

**Pull request merged**
